# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
    ports:
      - 10010:10000
      - 10011:10001
      - 10012:10002
    volumes:
      - ./azurite:/workspace

  dotnetmonitor:
    image: mcr.microsoft.com/dotnet/monitor:7
    container_name: dotnetmonitor
    environment:
      - DOTNETMONITOR_DiagnosticPort__ConnectionMode=Listen
      - DOTNETMONITOR_Storage__DefaultSharedPath=/tmp
      - DOTNETMONITOR_Urls=http://localhost:52323
      - DOTNETMONITOR_Metrics__Endpoints=http://+:52325
    ports:
      - 52323:52323
    volumes:
      - ./monitordata:/tmp
    command: [ "collect", "--no-auth" ]

  creditcheck:
    image: contosoloans/creditcheck
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SiloName=CreditCheck
      - DOTNET_DiagnosticPorts=/tmp/dotnet-monitor.sock
    build:
      context: .
      dockerfile: src/CreditCheck/Dockerfile
    volumes:
      - ./monitordata:/tmp
      - ./secrets:/secrets
    depends_on:
      - azurite
      - dotnetmonitor

  loanreception:
    image: contosoloans/loanreception
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SiloName=LoanReception
      - DOTNET_DiagnosticPorts=/tmp/dotnet-monitor.sock
    build:
      context: .
      dockerfile: src/LoanReception/Dockerfile
    volumes:
      - ./monitordata:/tmp
      - ./secrets:/secrets
    depends_on:
      - azurite
      - creditcheck
      - dotnetmonitor

  loanprocessmonitor:
    image: contosoloans/loanprocessmonitor
    ports:
      - 5003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SiloName=LoanProcessMonitor
      - DOTNET_DiagnosticPorts=/tmp/dotnet-monitor.sock
    build:
      context: .
      dockerfile: src/LoanProcessMonitor/Dockerfile
    volumes:
      - ./monitordata:/tmp
      - ./secrets:/secrets
    depends_on:
      - loanreception
      - dotnetmonitor

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prom_data: