global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'CreditCheck'
    static_configs:
      - targets: ['creditcheck:80']
  - job_name: 'LoanReception'
    static_configs:
      - targets: ['loanreception:80']
  - job_name: 'LoanProcessMonitor'
    static_configs:
      - targets: ['loanprocessmonitor:80']
  - job_name: 'dotnet monitor'
    static_configs:
      - targets: ['dotnetmonitor:52325']